trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

parameters:

- name: service
  type: string
  default: microservice-repo1
  values: 
  - microservice-repo1
  - microservice2
  - microservice3

- name: ticketId
  type: string
  default: ''
  displayName: 'Task or Ticket ID'

variables:
 - group: PipelineOfPipeline
 - name: organization
   value: arun4duraisamy0719
 - name: project
   value: Bicep-demo
 - name: git_user_name
   value: 'Arun Duraisamy'
 - name: git_user_email
   value: 'Arun4.Duraisamy@gmail.com'


stages:

- stage: 'validate_microservice_stage'
  jobs:
  - job: 'validate_microservice_job'
    steps:
    - script: |
        pip install azure-devops
      displayName: 'Install Azure DevOps CLI'
        
    - task: AzureCLI@2
      displayName: 'Git Repositoy creation script'
      inputs:
        azureSubscription: 'BicepDeploymentConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          ./createRepository.sh "https://dev.azure.com/$(organization)" "$(project)" "${{ parameters.service }}"
      env:
        AZURE_DEVOPS_PAT: $(AZURE_DEVOPS_PAT) 

    - task: AzureCLI@2
      displayName: 'Clone the target repository'
      inputs:
        azureSubscription: 'BicepDeploymentConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          git clone https://$(AZURE_DEVOPS_PAT)@dev.azure.com/$(targetRepo).git target-repo
          cd target-repo
          cp ../src/bicep/azure-pipeline.yml azure-pipeline.yml 
          git config --global user.email "$git_user_email"
          git config --global user.name "$git_user_name"
          git add azure-pipeline.yml 
          git commit -m "Add azure-pipeline.yml file via Azure Pipeline"
          git push https://$(AZURE_DEVOPS_PAT)@dev.azure.com/$(targetRepo).git
      env:
        AZURE_DEVOPS_PAT: $(AZURE_DEVOPS_PAT) 
        targetRepo: 'arun4duraisamy0719/Bicep-demo/_git/${{ parameters.service }}'
        git_user_name: $(git_user_name)
        git_user_email: $(git_user_email)
        
    - task: AzureCLI@2
      displayName: 'Release Pipeline creation script'
      inputs:
        azureSubscription: 'BicepDeploymentConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          ./createReleasePipeline.sh "https://dev.azure.com/$(organization)" "$(project)" "${{ parameters.service }}" "${{ parameters.service }}"
      env:
        AZURE_DEVOPS_PAT: $(AZURE_DEVOPS_PAT)        
