trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

parameters:

- name: service
  type: string
  default: microservice-repo1
  values: 
  - microservice-repo1
  - microservice2
  - microservice3
- name: AuthorizationHeaderText
  type: string
  default: ''
  displayName: 'Auth header text'
- name: ticketId
  type: string
  default: ''
  displayName: 'Task or Ticket ID'

stages:

- stage: 'validate_microservice_stage'
  jobs:
  - job: 'validate_microservice_job'
    steps:
    - script: |
        ./createRepo.sh "$service" "$AuthorizationHeaderText"
      displayName: 'Run Create Repo sript'
      env:
        service: '${{ parameters.service }}'
        AuthorizationHeaderText: ${{ parameters.AuthorizationHeaderText }}